# SITE SETUP
# Guide: https://hugoblox.com/docs/getting-started/
# Documentation: https://hugoblox.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: ocean
  theme_night: ocean
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: ''
    google_tag_manager: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-gb

# Contact (edit or remove options as required)

email: tong.wang@ed.ac.uk
phone: +44 131 651 5551
address:
  street: 29 Buccleuch Place
  city: Edinburgh
  region: Scotland
  postcode: 'EH8 9JS'
  country: United Kingdom
  country_code: UK

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
  math:
    enable: true
  diagram:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: ''
    content_dir: ''
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
